on:
#  push:
#    branches:
#      - 'main'
  workflow_dispatch:
jobs:
  ecr-deploy:
    uses: ./.github/workflows/docker-build-and-ecr-deploy.yml
    with:
      docker_image_name: 'item-to-row'
      build_dir: 'item-to-row'
      ecr_registry_path: 'mk-fn'
    secrets:
      AWS_OPEN_ID_CONNECT_ROLE_ARN: ${{ secrets.AWS_OPEN_ID_CONNECT_ROLE_ARN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}