name: IMAGE-DEPLOY
on:
  workflow_dispatch:
permissions:
  id-token: write  # required by aws-actions/configure-aws-credentials
  contents: write  # to push new git tag
jobs:
  ecr-deploy:
    uses: ./.github/workflows/docker-build-and-ecr-deploy.yml
    with:
      docker_image_name: 'item-to-row'
      build_dir: 'item-to-row'
      ecr_registry_path: 'mk-fn'
    secrets:
      ROLE_ARN: ${{ secrets.ROLE_ARN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}